[versions]
base45 = "0.0.3"
bouncyCastle = "1.70"
cbor = "0.01.02"
commonsCompress = "1.21"
commonsCodec = "1.15"
coseJava = "1.1.0"
jsonSimple = "0.4"
mockWebServer = "4.9.3"
nimbusJoseJwt = "9.23"
openapi = "1.6.8"
springBoot = "2.7.0"
webFlux = "2.7.0"
zxing = "3.5.0"
