[versions]
openapi = "1.6.8"
base45 = "0.0.3"
zxing = "3.5.0"
cbor = "0.01.02"
coseJava = "1.1.0"
jsonSimple = "0.4"
commonsCodec = "1.15"
webFlux = "2.7.0"
mockWebServer = "4.9.3"
bouncyCastle = "1.70"
commonsCompress = "1.21"
