server:
  compression:
    enabled: true
  port: 8082

spring:
  application:
    name: decovid-19-core
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  endpoint.health.show-details: always

#logging:
#  file.name: 'logs/${spring.application.name}.log'
#  logback:
#    rollingpolicy:
#      file-name-pattern: 'logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log'
#      max-file-size: 20MB
#      max-history: 100
#      clean-history-on-start: true
