name: CI decovid-19-core

on:
  push:
    branches: [ 'main' ]
    tags:
      - '*'
  pull_request:
    branches: [ '**' ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test sonarqube --tests "*"

      - name: Test Report
        if: success() || failure()
        uses: dorny/test-reporter@v1.5.0
        with:
          name: Test Report
          path: '**/build/test-results/test/TEST-*.xml'
          reporter: java-junit
